extern int redirecting_sys_open(const char *pathname, int oflags, mode_t mode);
extern int (*orig_sys_open)(const char *pathname, int oflags, mode_t mode);
extern int redirecting_sys_creat(const char *pathname, mode_t mode);
extern int (*orig_sys_creat)(const char *pathname, mode_t mode);
extern int redirecting_sys_truncate(const char *path, off_t length);
extern int (*orig_sys_truncate)(const char *path, off_t length);
extern int redirecting_sys_truncate64(const char *path, loff_t length);
extern int (*orig_sys_truncate64)(const char *path, loff_t length);
extern int redirecting_sys_stat(const char *file_name, struct stat *buf);
extern int (*orig_sys_stat)(const char *file_name, struct stat *buf);
extern int redirecting_sys_lstat(const char *file_name, struct stat *buf);
extern int (*orig_sys_lstat)(const char *file_name, struct stat *buf);
extern int redirecting_sys_stat64(const char *file_name, struct stat64 *buf);
extern int (*orig_sys_stat64)(const char *file_name, struct stat64 *buf);
extern int redirecting_sys_lstat64(const char *file_name, struct stat64 *buf);
extern int (*orig_sys_lstat64)(const char *file_name, struct stat64 *buf);
extern int redirecting_sys_access(const char *pathname, int mode);
extern int (*orig_sys_access)(const char *pathname, int mode);
extern int redirecting_sys_readlink(const char *path, char *buf, size_t bufsiz);
extern int (*orig_sys_readlink)(const char *path, char *buf, size_t bufsiz);
extern int redirecting_sys_rename(const char *oldpath, const char *newpath);
extern int (*orig_sys_rename)(const char *oldpath, const char *newpath);
extern int redirecting_sys_unlink(const char *pathname);
extern int (*orig_sys_unlink)(const char *pathname);
extern int redirecting_sys_chdir(const char *path);
extern int (*orig_sys_chdir)(const char *path);
extern int redirecting_sys_mkdir(const char *pathname, mode_t mode);
extern int (*orig_sys_mkdir)(const char *pathname, mode_t mode);
extern int redirecting_sys_rmdir(const char *pathname);
extern int (*orig_sys_rmdir)(const char *pathname);
extern int redirecting_sys_chmod(const char *path, mode_t mode);
extern int (*orig_sys_chmod)(const char *path, mode_t mode);
extern int redirecting_sys_chown(const char *path, uid_t owner, gid_t group);
extern int (*orig_sys_chown)(const char *path, uid_t owner, gid_t group);
extern int redirecting_sys_lchown(const char *path, uid_t owner, gid_t group);
extern int (*orig_sys_lchown)(const char *path, uid_t owner, gid_t group);
extern int redirecting_sys_chown32(const char *path, uid_t owner, gid_t group);
extern int (*orig_sys_chown32)(const char *path, uid_t owner, gid_t group);
extern int redirecting_sys_lchown32(const char *path, uid_t owner, gid_t group);
extern int (*orig_sys_lchown32)(const char *path, uid_t owner, gid_t group);
extern int redirecting_sys_mknod(const char *pathname, mode_t mode, dev_t dev);
extern int (*orig_sys_mknod)(const char *pathname, mode_t mode, dev_t dev);
extern int redirecting_sys_link(const char *oldpath, const char *newpath);
extern int (*orig_sys_link)(const char *oldpath, const char *newpath);
extern int redirecting_sys_symlink(const char *oldpath, const char *newpath);
extern int (*orig_sys_symlink)(const char *oldpath, const char *newpath);
extern int redirecting_sys_utime(const char *filename, const struct utimbuf *buf);
extern int (*orig_sys_utime)(const char *filename, const struct utimbuf *buf);
extern int redirecting_sys_swapon(const char *path, int swapflags);
extern int (*orig_sys_swapon)(const char *path, int swapflags);
extern int redirecting_sys_swapoff(const char *path);
extern int (*orig_sys_swapoff)(const char *path);
extern int redirecting_sys_getdents(unsigned int fd, struct dirent *dirp, unsigned int count);
extern int (*orig_sys_getdents)(unsigned int fd, struct dirent *dirp, unsigned int count);
extern int redirecting_sys_getdents64(unsigned int fd, struct dirent64 *dirp, unsigned int count);
extern int (*orig_sys_getdents64)(unsigned int fd, struct dirent64 *dirp, unsigned int count);
extern int redirecting_sys_execve(const char *filename, char *const argv [], char *const envp[]);
extern int (*orig_sys_execve)(const char *filename, char *const argv [], char *const envp[]);
